name: Build Packs

on:
  workflow_dispatch:

jobs:
  build:
    uses: TiNYsx/auto-rp-converter/.github/workflows/build-pack.yml@main
    with:
      input_root: .
      out_dir: __packfile
      compact: false
    secrets: inherit